# Generated by Django 6.0 on 2025-12-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("common_names", models.JSONField(help_text="List of common names")),
                ("scientific_name", models.CharField(max_length=200, unique=True)),
                ("plant_family", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("habitat", models.CharField(blank=True, max_length=200)),
                (
                    "regions",
                    models.JSONField(
                        default=list, help_text="Geographical regions where found"
                    ),
                ),
                (
                    "traditional_systems",
                    models.JSONField(
                        default=list,
                        help_text="Traditional medicine systems (Ayurveda, TCM, etc.)",
                    ),
                ),
                (
                    "cultural_uses",
                    models.JSONField(
                        default=list, help_text="Cultural and historical uses"
                    ),
                ),
                (
                    "parts_used",
                    models.JSONField(
                        default=list, help_text="Plant parts used medicinally"
                    ),
                ),
                (
                    "preparations",
                    models.JSONField(
                        default=list, help_text="Traditional preparation methods"
                    ),
                ),
                (
                    "dosage_info",
                    models.TextField(
                        blank=True, help_text="Traditional dosage information"
                    ),
                ),
                (
                    "active_compounds",
                    models.JSONField(default=list, help_text="Known active compounds"),
                ),
                (
                    "research_studies",
                    models.JSONField(
                        default=list, help_text="Scientific studies and findings"
                    ),
                ),
                (
                    "pharmacological_actions",
                    models.JSONField(default=list, help_text="Pharmacological effects"),
                ),
                ("safety_warnings", models.TextField(blank=True)),
                ("contraindications", models.TextField(blank=True)),
                ("interactions", models.TextField(blank=True)),
                ("toxicity_info", models.TextField(blank=True)),
                ("conservation_status", models.CharField(blank=True, max_length=50)),
                ("sustainability_info", models.TextField(blank=True)),
                ("ethical_sourcing", models.TextField(blank=True)),
                (
                    "image_url",
                    models.URLField(blank=True, help_text="Plant illustration URL"),
                ),
                ("image_credit", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["scientific_name"],
            },
        ),
    ]
