from django.core.management.base import BaseCommand
from plants.models import Plant

class Command(BaseCommand):
    help = 'Seed the database with sample medicinal plants'

    def handle(self, *args, **options):
        self.stdout.write("Starting seed_plants command...")
        # African medicinal plants data - focusing on Kenya and other African regions
        plants_data = [
            # Kenya - Moringa (widespread)
            {
                "common_names": ["Moringa", "Drumstick Tree", "Horseradish Tree"],
                "scientific_name": "Moringa oleifera",
                "plant_family": "Moringaceae",
                "description": "A fast-growing tree native to tropical and subtropical regions, widely cultivated in Kenya for its nutritious leaves and medicinal properties.",
                "habitat": "Tropical and subtropical regions, widely cultivated in Kenya",
                "regions": ["Kenya", "East Africa", "West Africa", "South Asia"],
                "traditional_systems": ["African Traditional Medicine", "Ayurveda"],
                "cultural_uses": ["Nutritional supplement", "Water purification", "Diabetes management", "Anti-inflammatory"],
                "parts_used": ["Leaves", "Pods", "Seeds", "Roots"],
                "preparations": ["Tea", "Powder", "Oil", "Fresh leaves"],
                "dosage_info": "10-20g dried leaves daily, 1-2g seed powder",
                "active_compounds": ["Quercetin", "Chlorogenic acid", "Vitamin C", "Iron"],
                "research_studies": ["Antidiabetic effects", "Antioxidant properties", "Nutritional benefits"],
                "pharmacological_actions": ["Hypoglycemic", "Antioxidant", "Anti-inflammatory", "Antimicrobial"],
                "safety_warnings": "May interact with diabetes medications",
                "contraindications": "Pregnancy (roots), Thyroid conditions",
                "interactions": "Diabetes medications",
                "toxicity_info": "Generally safe, but high doses may cause digestive upset",
                "conservation_status": "Not endangered",
                "sustainability_info": "Widely cultivated, sustainable",
                "ethical_sourcing": "Choose organic, fair trade certified",
                "image_url": "https://example.com/moringa.jpg",
                "image_credit": "Public domain botanical illustration",
                "is_verified": True,
            },
            # Kenya - Mt Kenya region
            {
                "common_names": ["East African Greenheart", "Uganda Greenheart"],
                "scientific_name": "Warburgia ugandensis",
                "plant_family": "Canellaceae",
                "description": "An evergreen tree found in the montane forests of East Africa, highly valued for its medicinal bark.",
                "habitat": "Montane forests of East Africa, Mt Kenya region",
                "regions": ["Kenya", "Uganda", "Tanzania"],
                "traditional_systems": ["East African Traditional Medicine"],
                "cultural_uses": ["Antimalarial", "Antimicrobial", "Fever treatment", "Respiratory infections"],
                "parts_used": ["Bark", "Leaves"],
                "preparations": ["Decoction", "Powder", "Tincture"],
                "dosage_info": "5-10g bark decoction, 2-3 times daily",
                "active_compounds": ["Warburganal", "Muzigadial", "Polgodial"],
                "research_studies": ["Antimalarial activity", "Antimicrobial effects"],
                "pharmacological_actions": ["Antimalarial", "Antimicrobial", "Antipyretic"],
                "safety_warnings": "May cause gastrointestinal irritation",
                "contraindications": "Pregnancy, Children under 12",
                "interactions": "None documented",
                "toxicity_info": "Low toxicity but may cause nausea",
                "conservation_status": "Vulnerable",
                "sustainability_info": "Protected species, sustainable harvesting needed",
                "ethical_sourcing": "Wildcrafted from sustainable sources",
                "image_url": "https://example.com/warburgia.jpg",
                "image_credit": "Botanical illustration",
                "is_verified": True,
            },
            # Kenya - Pygeum (Central Kenya forests)
            {
                "common_names": ["Pygeum", "African Cherry", "Red Stinkwood"],
                "scientific_name": "Prunus africana",
                "plant_family": "Rosaceae",
                "description": "An evergreen tree found in the montane forests of Central and Southern Africa, bark used for prostate health.",
                "habitat": "Montane forests, Mt Kenya and Aberdare ranges",
                "regions": ["Kenya", "Cameroon", "Democratic Republic of Congo"],
                "traditional_systems": ["African Traditional Medicine", "Western Phytotherapy"],
                "cultural_uses": ["Prostate health", "Benign prostatic hyperplasia", "Urinary tract health"],
                "parts_used": ["Bark"],
                "preparations": ["Extract", "Capsules", "Tea"],
                "dosage_info": "100-200mg extract daily",
                "active_compounds": ["Beta-sitosterol", "Pentacyclic triterpenes"],
                "research_studies": ["BPH treatment", "Prostate health"],
                "pharmacological_actions": ["Anti-inflammatory", "5-alpha reductase inhibitor"],
                "safety_warnings": "May cause mild gastrointestinal upset",
                "contraindications": "None documented",
                "interactions": "None significant",
                "toxicity_info": "Generally safe",
                "conservation_status": "Endangered",
                "sustainability_info": "CITES protected, sustainable cultivation needed",
                "ethical_sourcing": "Choose certified sustainable sources",
                "image_url": "https://example.com/pygeum.jpg",
                "image_credit": "Botanical illustration",
                "is_verified": True,
            },
            # Kenya - Coastal region
            {
                "common_names": ["East African Satinwood", "Mkundu"],
                "scientific_name": "Zanthoxylum usambarense",
                "plant_family": "Rutaceae",
                "description": "A tree found in coastal forests of East Africa, traditionally used for toothache and infections.",
                "habitat": "Coastal forests, Kenya and Tanzania",
                "regions": ["Kenya", "Tanzania"],
                "traditional_systems": ["East African Traditional Medicine"],
                "cultural_uses": ["Toothache relief", "Antimicrobial", "Pain relief", "Oral health"],
                "parts_used": ["Bark", "Roots"],
                "preparations": ["Decoction", "Powder", "Chewing sticks"],
                "dosage_info": "As needed for toothache",
                "active_compounds": ["Alkaloids", "Limonoids"],
                "research_studies": ["Antimicrobial activity", "Analgesic effects"],
                "pharmacological_actions": ["Analgesic", "Antimicrobial", "Local anesthetic"],
                "safety_warnings": "May cause numbness",
                "contraindications": "None documented",
                "interactions": "None documented",
                "toxicity_info": "Safe for external use",
                "conservation_status": "Vulnerable",
                "sustainability_info": "Protected species",
                "ethical_sourcing": "Sustainable wildcrafting",
                "image_url": "https://example.com/zanthoxylum.jpg",
                "image_credit": "Botanical illustration",
                "is_verified": True,
            },
            # Kenya - Khat (Meru region)
            {
                "common_names": ["Khat", "Miraa", "Qa'at"],
                "scientific_name": "Catha edulis",
                "plant_family": "Celastraceae",
                "description": "An evergreen shrub native to East Africa, leaves chewed for stimulant effects.",
                "habitat": "Highlands of East Africa, Meru region Kenya",
                "regions": ["Kenya", "Ethiopia", "Somalia", "Yemen"],
                "traditional_systems": ["East African Traditional Medicine", "Middle Eastern Traditional Medicine"],
                "cultural_uses": ["Stimulant", "Appetite suppression", "Social ceremonies"],
                "parts_used": ["Fresh leaves"],
                "preparations": ["Chewing fresh leaves"],
                "dosage_info": "Fresh leaves as needed",
                "active_compounds": ["Cathinone", "Cathine", "Norephedrine"],
                "research_studies": ["Stimulant effects", "Amphetamine-like activity"],
                "pharmacological_actions": ["CNS stimulant", "Appetite suppressant"],
                "safety_warnings": "Addictive potential, cardiovascular effects",
                "contraindications": "Heart conditions, Pregnancy, Anxiety disorders",
                "interactions": "MAOIs, Antidepressants",
                "toxicity_info": "Psychoactive, potential for abuse",
                "conservation_status": "Not endangered",
                "sustainability_info": "Major cash crop in Kenya",
                "ethical_sourcing": "Regulated cultivation",
                "image_url": "https://example.com/khat.jpg",
                "image_credit": "Botanical illustration",
                "is_verified": True,
            },
            # Kenya - Aloe (Rift Valley)
            {
                "common_names": ["Kenya Aloe", "Aloe secundiflora"],
                "scientific_name": "Aloe secundiflora",
                "plant_family": "Asphodelaceae",
                "description": "A succulent plant native to Kenya's Rift Valley, used for skin conditions and wound healing.",
                "habitat": "Rocky hillsides in Kenya's Rift Valley",
                "regions": ["Kenya"],
                "traditional_systems": ["East African Traditional Medicine"],
                "cultural_uses": ["Wound healing", "Skin conditions", "Burn treatment"],
                "parts_used": ["Gel", "Leaves"],
                "preparations": ["Gel application", "Poultice"],
                "dosage_info": "Topical application as needed",
                "active_compounds": ["Aloin", "Anthraquinones"],
                "research_studies": ["Wound healing properties", "Anti-inflammatory effects"],
                "pharmacological_actions": ["Anti-inflammatory", "Antimicrobial", "Wound healing"],
                "safety_warnings": "May cause skin irritation",
                "contraindications": "None for topical use",
                "interactions": "None documented",
                "toxicity_info": "Safe for external use",
                "conservation_status": "Vulnerable",
                "sustainability_info": "Protected species in Kenya",
                "ethical_sourcing": "Sustainable harvesting",
                "image_url": "https://example.com/aloe-kenya.jpg",
                "image_credit": "Botanical illustration",
                "is_verified": True,
            },
            # Southern Africa - Sutherlandia
            {
                "common_names": ["Cancer Bush", "Kankerbos"],
                "scientific_name": "Sutherlandia frutescens",
                "plant_family": "Fabaceae",
                "description": "A shrub native to Southern Africa, traditionally used for cancer treatment and immune support.",
                "habitat": "Dry regions of Southern Africa",
                "regions": ["South Africa", "Namibia", "Botswana"],
                "traditional_systems": ["Southern African Traditional Medicine"],
                "cultural_uses": ["Cancer treatment", "Immune support", "Stress relief", "HIV/AIDS support"],
                "parts_used": ["Leaves", "Stems"],
                "preparations": ["Tea", "Tincture", "Capsules"],
                "dosage_info": "300-600mg daily",
                "active_compounds": ["L-Canavanine", "GABA", "Sutherlandiosides"],
                "research_studies": ["Anticancer activity", "Immune modulation"],
                "pharmacological_actions": ["Immunomodulatory", "Anticancer", "Adaptogenic"],
                "safety_warnings": "May interact with chemotherapy",
                "contraindications": "Pregnancy, Autoimmune diseases",
                "interactions": "Immunosuppressants, Chemotherapy drugs",
                "toxicity_info": "Generally safe",
                "conservation_status": "Near threatened",
                "sustainability_info": "Cultivated for medicinal use",
                "ethical_sourcing": "Choose certified organic",
                "image_url": "https://example.com/sutherlandia.jpg",
                "image_credit": "Botanical illustration",
                "is_verified": True,
            },
            # Southern Africa - Devil's claw
            {
                "common_names": ["Devil's Claw", "Grapple Plant"],
                "scientific_name": "Harpagophytum procumbens",
                "plant_family": "Pedaliaceae",
                "description": "A plant native to Southern Africa, used for joint pain and inflammation.",
                "habitat": "Kalahari Desert regions",
                "regions": ["South Africa", "Namibia", "Botswana"],
                "traditional_systems": ["Southern African Traditional Medicine", "European Phytotherapy"],
                "cultural_uses": ["Arthritis relief", "Joint pain", "Anti-inflammatory", "Digestive aid"],
                "parts_used": ["Tubers"],
                "preparations": ["Extract", "Capsules", "Tea"],
                "dosage_info": "600-1200mg daily",
                "active_compounds": ["Harpagoside", "Harpagide"],
                "research_studies": ["Osteoarthritis treatment", "Anti-inflammatory effects"],
                "pharmacological_actions": ["Anti-inflammatory", "Analgesic", "Antirheumatic"],
                "safety_warnings": "May cause gastrointestinal upset",
                "contraindications": "Peptic ulcers, Gallstones",
                "interactions": "Blood thinners, Acid-reducing medications",
                "toxicity_info": "Generally safe",
                "conservation_status": "Vulnerable",
                "sustainability_info": "Cultivated in some areas",
                "ethical_sourcing": "Choose sustainable sources",
                "image_url": "https://example.com/devils-claw.jpg",
                "image_credit": "Botanical illustration",
                "is_verified": True,
            },
            # Southern Africa - African potato
            {
                "common_names": ["African Potato", "Sterretjie"],
                "scientific_name": "Hypoxis hemerocallidea",
                "plant_family": "Hypoxidaceae",
                "description": "A perennial plant native to Southern Africa, used for prostate health and immune support.",
                "habitat": "Grasslands of Southern Africa",
                "regions": ["South Africa", "Swaziland", "Zimbabwe"],
                "traditional_systems": ["Southern African Traditional Medicine"],
                "cultural_uses": ["Prostate health", "Immune support", "Anti-inflammatory"],
                "parts_used": ["Corms"],
                "preparations": ["Extract", "Capsules", "Tea"],
                "dosage_info": "500-1000mg daily",
                "active_compounds": ["Hypoxoside", "Roxburghoside"],
                "research_studies": ["Prostate health", "Immune modulation"],
                "pharmacological_actions": ["Immunomodulatory", "Anti-inflammatory", "Antioxidant"],
                "safety_warnings": "May cause mild gastrointestinal upset",
                "contraindications": "None documented",
                "interactions": "None significant",
                "toxicity_info": "Generally safe",
                "conservation_status": "Near threatened",
                "sustainability_info": "Wild harvested, sustainable practices needed",
                "ethical_sourcing": "Choose certified sustainable",
                "image_url": "https://example.com/african-potato.jpg",
                "image_credit": "Botanical illustration",
                "is_verified": True,
            },
            # Southern Africa - African wormwood
            {
                "common_names": ["African Wormwood", "Lanyana"],
                "scientific_name": "Artemisia afra",
                "plant_family": "Asteraceae",
                "description": "A perennial herb native to Southern Africa, used for respiratory conditions and fever.",
                "habitat": "Mountainous regions of Southern Africa",
                "regions": ["South Africa", "Lesotho", "Zimbabwe"],
                "traditional_systems": ["Southern African Traditional Medicine"],
                "cultural_uses": ["Cough relief", "Fever treatment", "Respiratory infections", "Wound healing"],
                "parts_used": ["Leaves", "Flowering tops"],
                "preparations": ["Tea", "Steam inhalation", "Tincture"],
                "dosage_info": "2-4 cups tea daily",
                "active_compounds": ["Artemisia ketone", "Camphor", "1,8-Cineole"],
                "research_studies": ["Antimicrobial activity", "Antiviral effects"],
                "pharmacological_actions": ["Antimicrobial", "Antiviral", "Expectorant"],
                "safety_warnings": "May cause allergic reactions",
                "contraindications": "Pregnancy, Epilepsy",
                "interactions": "None documented",
                "toxicity_info": "Safe in normal amounts",
                "conservation_status": "Not endangered",
                "sustainability_info": "Widely available, sustainable harvesting",
                "ethical_sourcing": "Wildcrafted responsibly",
                "image_url": "https://example.com/african-wormwood.jpg",
                "image_credit": "Botanical illustration",
                "is_verified": True,
            },
            # South Africa - Umckaloabo
            {
                "common_names": ["Umckaloabo", "South African Geranium"],
                "scientific_name": "Pelargonium sidoides",
                "plant_family": "Geraniaceae",
                "description": "A perennial herb native to South Africa, used for respiratory tract infections.",
                "habitat": "Grasslands of South Africa",
                "regions": ["South Africa"],
                "traditional_systems": ["Southern African Traditional Medicine", "European Phytotherapy"],
                "cultural_uses": ["Bronchitis treatment", "Common cold", "Sinusitis", "Tonsillitis"],
                "parts_used": ["Roots"],
                "preparations": ["Extract", "Tea", "Tincture"],
                "dosage_info": "30 drops extract, 3 times daily",
                "active_compounds": ["Coumarins", "Flavonoids"],
                "research_studies": ["Acute bronchitis treatment", "Antiviral activity"],
                "pharmacological_actions": ["Antiviral", "Immunomodulatory", "Anti-inflammatory"],
                "safety_warnings": "May cause mild gastrointestinal upset",
                "contraindications": "None documented",
                "interactions": "None significant",
                "toxicity_info": "Generally safe",
                "conservation_status": "Near threatened",
                "sustainability_info": "Cultivated for medicinal use",
                "ethical_sourcing": "Choose organic certified",
                "image_url": "https://example.com/umckaloabo.jpg",
                "image_credit": "Botanical illustration",
                "is_verified": True,
            },
            # South Africa - Rooibos
            {
                "common_names": ["Rooibos", "Red Bush Tea"],
                "scientific_name": "Aspalathus linearis",
                "plant_family": "Fabaceae",
                "description": "An endemic South African shrub, leaves used to make caffeine-free herbal tea.",
                "habitat": "Cederberg Mountains, South Africa",
                "regions": ["South Africa"],
                "traditional_systems": ["Khoisan Traditional Medicine"],
                "cultural_uses": ["Antioxidant", "Digestive health", "Skin conditions", "Relaxation"],
                "parts_used": ["Leaves", "Stems"],
                "preparations": ["Tea", "Extract"],
                "dosage_info": "2-3 cups tea daily",
                "active_compounds": ["Flavonoids", "Antioxidants", "Aspalathin"],
                "research_studies": ["Antioxidant effects", "Anti-allergic properties"],
                "pharmacological_actions": ["Antioxidant", "Anti-allergic", "Anti-inflammatory"],
                "safety_warnings": "None documented",
                "contraindications": "None documented",
                "interactions": "None documented",
                "toxicity_info": "Safe, caffeine-free",
                "conservation_status": "Near threatened",
                "sustainability_info": "Major agricultural crop in South Africa",
                "ethical_sourcing": "Choose fair trade certified",
                "image_url": "https://example.com/rooibos.jpg",
                "image_credit": "Botanical illustration",
                "is_verified": True,
            },
            # South Africa - Kanna
            {
                "common_names": ["Kanna", "Channa", "Kougoed"],
                "scientific_name": "Sceletium tortuosum",
                "plant_family": "Aizoaceae",
                "description": "A succulent plant native to South Africa, traditionally used as a mood enhancer and anxiolytic.",
                "habitat": "Western Cape region, South Africa",
                "regions": ["South Africa"],
                "traditional_systems": ["Khoisan Traditional Medicine"],
                "cultural_uses": ["Mood enhancement", "Anxiety relief", "Stress reduction", "Appetite suppression"],
                "parts_used": ["Leaves"],
                "preparations": ["Chewed fresh", "Extract", "Capsules"],
                "dosage_info": "50-300mg extract daily",
                "active_compounds": ["Mesembrine", "Mesembrenone"],
                "research_studies": ["Anxiolytic effects", "Antidepressant activity"],
                "pharmacological_actions": ["Serotonin reuptake inhibitor", "Anxiolytic", "Antidepressant"],
                "safety_warnings": "May cause mild euphoria",
                "contraindications": "Pregnancy, MAOI use",
                "interactions": "SSRIs, MAOIs",
                "toxicity_info": "Generally safe at recommended doses",
                "conservation_status": "Vulnerable",
                "sustainability_info": "Protected species, cultivation ongoing",
                "ethical_sourcing": "Choose cultivated sources",
                "image_url": "https://example.com/kanna.jpg",
                "image_credit": "Botanical illustration",
                "is_verified": True,
            },
            # Southern Africa - African ginger
            {
                "common_names": ["African Ginger", "Wild Ginger"],
                "scientific_name": "Siphonochilus aethiopicus",
                "plant_family": "Zingiberaceae",
                "description": "A rare ginger native to Southern Africa, used for respiratory and digestive conditions.",
                "habitat": "Moist forests of Southern Africa",
                "regions": ["South Africa", "Swaziland"],
                "traditional_systems": ["Southern African Traditional Medicine"],
                "cultural_uses": ["Cough relief", "Bronchitis treatment", "Digestive aid", "Anti-inflammatory"],
                "parts_used": ["Rhizome"],
                "preparations": ["Tea", "Tincture", "Powder"],
                "dosage_info": "1-2g dried rhizome daily",
                "active_compounds": ["Sesquiterpenes", "Flavonoids"],
                "research_studies": ["Antimicrobial activity", "Anti-inflammatory effects"],
                "pharmacological_actions": ["Antimicrobial", "Anti-inflammatory", "Expectorant"],
                "safety_warnings": "May cause mild gastrointestinal upset",
                "contraindications": "Pregnancy, Children under 12",
                "interactions": "None documented",
                "toxicity_info": "Generally safe",
                "conservation_status": "Critically endangered",
                "sustainability_info": "Rare species, conservation efforts needed",
                "ethical_sourcing": "Cultivated sources only",
                "image_url": "https://example.com/african-ginger.jpg",
                "image_credit": "Botanical illustration",
                "is_verified": True,
            },
            # East Africa - Neem
            {
                "common_names": ["Neem", "Azadirachta", "Indian Lilac"],
                "scientific_name": "Azadirachta indica",
                "plant_family": "Meliaceae",
                "description": "A tree native to the Indian subcontinent but widely planted in East Africa, used for pest control and medicine.",
                "habitat": "Tropical regions, widely planted in Kenya",
                "regions": ["India", "Kenya", "Tanzania", "Uganda"],
                "traditional_systems": ["Ayurveda", "East African Traditional Medicine"],
                "cultural_uses": ["Pest control", "Skin conditions", "Antimicrobial", "Diabetes management"],
                "parts_used": ["Leaves", "Bark", "Seeds"],
                "preparations": ["Oil", "Tea", "Powder", "Extract"],
                "dosage_info": "5-10ml oil daily, 2-4g leaves daily",
                "active_compounds": ["Azadirachtin", "Quercetin", "Vitamin E"],
                "research_studies": ["Antimicrobial effects", "Antidiabetic properties"],
                "pharmacological_actions": ["Antimicrobial", "Antiviral", "Antifungal", "Antidiabetic"],
                "safety_warnings": "May cause kidney damage in high doses",
                "contraindications": "Pregnancy, Children under 5",
                "interactions": "Diabetes medications",
                "toxicity_info": "Safe in recommended doses",
                "conservation_status": "Not endangered",
                "sustainability_info": "Widely cultivated",
                "ethical_sourcing": "Choose organic",
                "image_url": "https://example.com/neem.jpg",
                "image_credit": "Botanical illustration",
                "is_verified": True,
            },
            # West Africa - Bitter leaf (also found in Kenya)
            {
                "common_names": ["Bitter Leaf", "Onugbu", "Ewuro"],
                "scientific_name": "Vernonia amygdalina",
                "plant_family": "Asteraceae",
                "description": "A shrub native to tropical Africa, leaves used for medicinal and culinary purposes.",
                "habitat": "Tropical Africa, also found in western Kenya",
                "regions": ["Nigeria", "Cameroon", "Kenya", "Ghana"],
                "traditional_systems": ["West African Traditional Medicine", "East African Traditional Medicine"],
                "cultural_uses": ["Malaria treatment", "Diabetes management", "Fever reduction", "Digestive health"],
                "parts_used": ["Leaves"],
                "preparations": ["Tea", "Soup", "Extract"],
                "dosage_info": "2-4 cups tea daily, 5-10g leaves daily",
                "active_compounds": ["Vernodalin", "Vernolepin", "Luteolin"],
                "research_studies": ["Antimalarial activity", "Antidiabetic effects"],
                "pharmacological_actions": ["Antimalarial", "Antidiabetic", "Antimicrobial", "Antioxidant"],
                "safety_warnings": "Bitter taste may cause nausea",
                "contraindications": "Pregnancy (high doses)",
                "interactions": "None significant",
                "toxicity_info": "Generally safe",
                "conservation_status": "Not endangered",
                "sustainability_info": "Widely available, sustainable",
                "ethical_sourcing": "Choose organic",
                "image_url": "https://example.com/bitter-leaf.jpg",
                "image_credit": "Botanical illustration",
                "is_verified": True,
            },
            # Kenya - Worm-cure tree
            {
                "common_names": ["Worm-cure Tree", "Winter Thorn"],
                "scientific_name": "Albizia anthelmintica",
                "plant_family": "Fabaceae",
                "description": "A tree found in arid regions of East Africa, bark used for parasitic infections.",
                "habitat": "Arid and semi-arid regions of Kenya",
                "regions": ["Kenya", "Ethiopia", "Somalia"],
                "traditional_systems": ["East African Traditional Medicine"],
                "cultural_uses": ["Anthelmintic", "Malaria treatment", "Fever reduction"],
                "parts_used": ["Bark", "Roots"],
                "preparations": ["Decoction", "Powder"],
                "dosage_info": "10-20g bark decoction daily",
                "active_compounds": ["Alkaloids", "Tannins", "Saponins"],
                "research_studies": ["Anthelmintic activity", "Antimalarial effects"],
                "pharmacological_actions": ["Anthelmintic", "Antimalarial", "Antipyretic"],
                "safety_warnings": "May cause gastrointestinal upset",
                "contraindications": "Pregnancy, Children under 5",
                "interactions": "None documented",
                "toxicity_info": "Generally safe at recommended doses",
                "conservation_status": "Not endangered",
                "sustainability_info": "Common in arid regions",
                "ethical_sourcing": "Sustainable wildcrafting",
                "image_url": "https://example.com/albizia.jpg",
                "image_credit": "Botanical illustration",
                "is_verified": True,
            },
            # Kenya - Gum arabic tree
            {
                "common_names": ["Gum Arabic Tree", "Hashab Tree"],
                "scientific_name": "Acacia senegal",
                "plant_family": "Fabaceae",
                "description": "A tree native to arid regions of Africa, source of gum arabic and medicinal uses.",
                "habitat": "Sahel region, northern Kenya",
                "regions": ["Sudan", "Chad", "Kenya", "Ethiopia"],
                "traditional_systems": ["Saharan Traditional Medicine", "East African Traditional Medicine"],
                "cultural_uses": ["Diarrhea treatment", "Sore throat relief", "Wound healing"],
                "parts_used": ["Gum", "Bark", "Leaves"],
                "preparations": ["Gum solution", "Decoction", "Powder"],
                "dosage_info": "5-10g gum daily",
                "active_compounds": ["Arabinogalactan", "Polysaccharides"],
                "research_studies": ["Prebiotic effects", "Anti-inflammatory properties"],
                "pharmacological_actions": ["Demulcent", "Prebiotic", "Anti-inflammatory"],
                "safety_warnings": "May cause allergic reactions",
                "contraindications": "None documented",
                "interactions": "None documented",
                "toxicity_info": "Safe, GRAS status",
                "conservation_status": "Not endangered",
                "sustainability_info": "Major gum arabic producer",
                "ethical_sourcing": "Choose fair trade certified",
                "image_url": "https://example.com/acacia-senegal.jpg",
                "image_credit": "Botanical illustration",
                "is_verified": True,
            },
            # Kenya - African basil
            {
                "common_names": ["African Basil", "Clove Basil"],
                "scientific_name": "Ocimum gratissimum",
                "plant_family": "Lamiaceae",
                "description": "A herb native to tropical Africa, widely used in western Kenya for medicinal and culinary purposes.",
                "habitat": "Tropical Africa, western Kenya",
                "regions": ["Kenya", "Nigeria", "Ghana", "Brazil"],
                "traditional_systems": ["West African Traditional Medicine", "East African Traditional Medicine"],
                "cultural_uses": ["Respiratory infections", "Fever treatment", "Antimicrobial", "Digestive aid"],
                "parts_used": ["Leaves", "Essential oil"],
                "preparations": ["Tea", "Steam inhalation", "Essential oil"],
                "dosage_info": "2-3 cups tea daily",
                "active_compounds": ["Eugenol", "Thymol", "Carvacrol"],
                "research_studies": ["Antimicrobial activity", "Antioxidant effects"],
                "pharmacological_actions": ["Antimicrobial", "Antioxidant", "Antipyretic", "Expectorant"],
                "safety_warnings": "May cause skin irritation (essential oil)",
                "contraindications": "None documented",
                "interactions": "None significant",
                "toxicity_info": "Generally safe",
                "conservation_status": "Not endangered",
                "sustainability_info": "Widely cultivated",
                "ethical_sourcing": "Choose organic",
                "image_url": "https://example.com/african-basil.jpg",
                "image_credit": "Botanical illustration",
                "is_verified": True,
            },
            # Kenya - Sodom apple
            {
                "common_names": ["Sodom Apple", "Devil's Tomato"],
                "scientific_name": "Solanum incanum",
                "plant_family": "Solanaceae",
                "description": "A shrub found in coastal Kenya, fruits and leaves used for skin conditions and infections.",
                "habitat": "Coastal regions of Kenya",
                "regions": ["Kenya", "Tanzania"],
                "traditional_systems": ["East African Coastal Traditional Medicine"],
                "cultural_uses": ["Skin infections", "Wound healing", "Antimicrobial", "Pain relief"],
                "parts_used": ["Leaves", "Fruits"],
                "preparations": ["Poultice", "Decoction", "Crushed leaves"],
                "dosage_info": "Topical application as needed",
                "active_compounds": ["Steroidal alkaloids", "Saponins"],
                "research_studies": ["Antimicrobial activity", "Wound healing properties"],
                "pharmacological_actions": ["Antimicrobial", "Anti-inflammatory", "Analgesic"],
                "safety_warnings": "Fruits may be toxic if ingested",
                "contraindications": "Pregnancy, Internal use of fruits",
                "interactions": "None documented",
                "toxicity_info": "Safe for external use, fruits toxic",
                "conservation_status": "Not endangered",
                "sustainability_info": "Common in coastal areas",
                "ethical_sourcing": "Sustainable wildcrafting",
                "image_url": "https://example.com/sodom-apple.jpg",
                "image_credit": "Botanical illustration",
                "is_verified": True,
            }
        ]

        # Seed the database
        self.stdout.write(f"Processing {len(plants_data)} plants...")
        created_count = 0
        for plant_data in plants_data:
            try:
                plant, created = Plant.objects.get_or_create(
                    scientific_name=plant_data['scientific_name'],
                    defaults=plant_data
                )
                if created:
                    created_count += 1
                    self.stdout.write(f"Created: {plant.scientific_name}")
                else:
                    self.stdout.write(f"Exists: {plant.scientific_name}")
            except Exception as e:
                self.stdout.write(f"Error creating {plant_data['scientific_name']}: {e}")

        self.stdout.write(self.style.SUCCESS(f"Database seeded with {created_count} new plants!"))